# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/luosu/codeproject/LuosuCompile

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/luosu/codeproject/LuosuCompile

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luosu/codeproject/LuosuCompile/CMakeFiles /home/luosu/codeproject/LuosuCompile//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luosu/codeproject/LuosuCompile/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LuosuCompileProject

# Build rule for target.
LuosuCompileProject: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LuosuCompileProject
.PHONY : LuosuCompileProject

# fast build rule for target.
LuosuCompileProject/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuosuCompileProject.dir/build.make CMakeFiles/LuosuCompileProject.dir/build
.PHONY : LuosuCompileProject/fast

#=============================================================================
# Target rules for targets named Helpers

# Build rule for target.
Helpers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Helpers
.PHONY : Helpers

# fast build rule for target.
Helpers/fast:
	$(MAKE) $(MAKESILENT) -f helpers/CMakeFiles/Helpers.dir/build.make helpers/CMakeFiles/Helpers.dir/build
.PHONY : Helpers/fast

compiler.o: compiler.c.o
.PHONY : compiler.o

# target to build an object file
compiler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuosuCompileProject.dir/build.make CMakeFiles/LuosuCompileProject.dir/compiler.c.o
.PHONY : compiler.c.o

compiler.i: compiler.c.i
.PHONY : compiler.i

# target to preprocess a source file
compiler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuosuCompileProject.dir/build.make CMakeFiles/LuosuCompileProject.dir/compiler.c.i
.PHONY : compiler.c.i

compiler.s: compiler.c.s
.PHONY : compiler.s

# target to generate assembly for a file
compiler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuosuCompileProject.dir/build.make CMakeFiles/LuosuCompileProject.dir/compiler.c.s
.PHONY : compiler.c.s

cprocess.o: cprocess.c.o
.PHONY : cprocess.o

# target to build an object file
cprocess.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuosuCompileProject.dir/build.make CMakeFiles/LuosuCompileProject.dir/cprocess.c.o
.PHONY : cprocess.c.o

cprocess.i: cprocess.c.i
.PHONY : cprocess.i

# target to preprocess a source file
cprocess.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuosuCompileProject.dir/build.make CMakeFiles/LuosuCompileProject.dir/cprocess.c.i
.PHONY : cprocess.c.i

cprocess.s: cprocess.c.s
.PHONY : cprocess.s

# target to generate assembly for a file
cprocess.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuosuCompileProject.dir/build.make CMakeFiles/LuosuCompileProject.dir/cprocess.c.s
.PHONY : cprocess.c.s

lex_process.o: lex_process.c.o
.PHONY : lex_process.o

# target to build an object file
lex_process.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuosuCompileProject.dir/build.make CMakeFiles/LuosuCompileProject.dir/lex_process.c.o
.PHONY : lex_process.c.o

lex_process.i: lex_process.c.i
.PHONY : lex_process.i

# target to preprocess a source file
lex_process.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuosuCompileProject.dir/build.make CMakeFiles/LuosuCompileProject.dir/lex_process.c.i
.PHONY : lex_process.c.i

lex_process.s: lex_process.c.s
.PHONY : lex_process.s

# target to generate assembly for a file
lex_process.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuosuCompileProject.dir/build.make CMakeFiles/LuosuCompileProject.dir/lex_process.c.s
.PHONY : lex_process.c.s

lexer.o: lexer.c.o
.PHONY : lexer.o

# target to build an object file
lexer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuosuCompileProject.dir/build.make CMakeFiles/LuosuCompileProject.dir/lexer.c.o
.PHONY : lexer.c.o

lexer.i: lexer.c.i
.PHONY : lexer.i

# target to preprocess a source file
lexer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuosuCompileProject.dir/build.make CMakeFiles/LuosuCompileProject.dir/lexer.c.i
.PHONY : lexer.c.i

lexer.s: lexer.c.s
.PHONY : lexer.s

# target to generate assembly for a file
lexer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuosuCompileProject.dir/build.make CMakeFiles/LuosuCompileProject.dir/lexer.c.s
.PHONY : lexer.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuosuCompileProject.dir/build.make CMakeFiles/LuosuCompileProject.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuosuCompileProject.dir/build.make CMakeFiles/LuosuCompileProject.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuosuCompileProject.dir/build.make CMakeFiles/LuosuCompileProject.dir/main.c.s
.PHONY : main.c.s

token.o: token.c.o
.PHONY : token.o

# target to build an object file
token.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuosuCompileProject.dir/build.make CMakeFiles/LuosuCompileProject.dir/token.c.o
.PHONY : token.c.o

token.i: token.c.i
.PHONY : token.i

# target to preprocess a source file
token.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuosuCompileProject.dir/build.make CMakeFiles/LuosuCompileProject.dir/token.c.i
.PHONY : token.c.i

token.s: token.c.s
.PHONY : token.s

# target to generate assembly for a file
token.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LuosuCompileProject.dir/build.make CMakeFiles/LuosuCompileProject.dir/token.c.s
.PHONY : token.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Helpers"
	@echo "... LuosuCompileProject"
	@echo "... compiler.o"
	@echo "... compiler.i"
	@echo "... compiler.s"
	@echo "... cprocess.o"
	@echo "... cprocess.i"
	@echo "... cprocess.s"
	@echo "... lex_process.o"
	@echo "... lex_process.i"
	@echo "... lex_process.s"
	@echo "... lexer.o"
	@echo "... lexer.i"
	@echo "... lexer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... token.o"
	@echo "... token.i"
	@echo "... token.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

